"""empty message

Revision ID: f0aa0cbb6d12
Revises: fa215ff1f134
Create Date: 2020-05-14 04:57:13.714642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0aa0cbb6d12'
down_revision = 'fa215ff1f134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('Show', 'id111')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('id111', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('Show', 'id')
    # ### end Alembic commands ###
