"""empty message

Revision ID: fa215ff1f134
Revises: 74b15143ea7d
Create Date: 2020-05-14 04:56:49.030103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa215ff1f134'
down_revision = '74b15143ea7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('id111', sa.Integer(), nullable=False))
    op.drop_column('Show', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('Show', 'id111')
    # ### end Alembic commands ###
