"""empty message

Revision ID: f9f430b79f4f
Revises: 7272e66fc6de
Create Date: 2020-05-14 02:57:25.322225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9f430b79f4f'
down_revision = '7272e66fc6de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('date_created', sa.DateTime(), nullable=False))
    op.add_column('Show', sa.Column('date_updated', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'date_updated')
    op.drop_column('Show', 'date_created')
    # ### end Alembic commands ###
